### ISSUE TITLE
opendds-example: issues when having OpenDDS compiled with security enabled

### ISSUE THREAD

**Issue by vermaete** [OpenDDS/meta-opendds#49]
The `opendds-example` recipe is working when I compile OpenDDS **without** security in the PACKAGECONFIG of the OpenDDS recipe. 
Security here is with `--security` in the `configure` and `openssl` and `xerces-c` are available.

However, the `opendds-example` is failing to configure when OpenDDS is configured **with** security.

As far as i know, the example itself doesn't use any feature of security.

The configuration error:

```
 CMake Error at /home/jan/projects/meta-opendds/build/tmp/work/core2-64-poky-linux/opendds-example/3.30.0/recipe-sysroot/usr/share/cmake/OpenDDS/opendds_group.cmake:76 (message):
|   Could not find OpenSSL
| Call Stack (most recent call first):
|   /home/jan/projects/meta-opendds/build/tmp/work/core2-64-poky-linux/opendds-example/3.30.0/recipe-sysroot/usr/share/cmake/OpenDDS/OpenDDSConfig.cmake:20 (include)
|   CMakeLists.txt:5 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!

```

The code of the `opendds_group.cmake`:

```
if(OPENDDS_SECURITY)
  find_package(OpenSSL PATHS "${OPENDDS_OPENSSL}" NO_DEFAULT_PATH QUIET)
  if(NOT OpenSSL_FOUND)
    set(OPENSSL_ROOT_DIR "${OPENDDS_OPENSSL}")
    find_package(OpenSSL QUIET)
  endif()
  if(NOT OpenSSL_FOUND)
    message(FATAL_ERROR "Could not find OpenSSL")
  endif()
endif()
```

I'm a bit lost why `OPENDDS_SECURITY` is on here?
Even when doing a `-DOPENDDS_SECURITY=OFF` with CMake.

Br,

**Comment by jrw972** [comment]
If OpenDDS is built with security, then openssl will always need to be linked.
The choice to use security is made at run-time so the libraries must still be available.

@iguessthislldo Thoughts?

**Comment by vermaete** [comment]
@jrw972 So the developer of an application do has to know how opendds is configured on a target because the cmake files (well, bitbake recipe in my case) should know the configuration of OpenDDS.
Well, it can work.  But is it not a bit weird in the case the application isn't using 'secured' at all?
Anyhow, it was just a thought when making the recipe of the example.
It can be close if you want.

**Comment by jrw972** [comment]
While this doesn't fix your problem, I think it is relevant.

An implicit assumption that has been in OpenDDS for a very long time is that users would use MPC to build their applications.  For users that didn't want to use MPC, we would recommend building it with MPC and using the generated Makefile, command-lines, etc. as examples for whatever build system they used.  With cmake, we are trying to do something similar so our goal is to have cmake support so that application developers don't need to know how OpenDDS was built to use it to the extent possible.  Since cmake is new, we are still working on it.

Related is the problem of determining how OpenDDS was built at compile time.  That is, an application may make use of optional features in OpenDDS so the application code needs to know if the feature was enabled or not.  Traditionally, this was done through command-line defines supplied through MPC.  Recently, we have started the process of storing these in a file so that eventually a user can just include the file instead of reverse engineering a command-line from MPC.  https://github.com/OpenDDS/OpenDDS/wiki/Proposal:-Header-file-for-compile%E2%80%90time-configuration
